export const LANDING_PAGE_PATH = '/'
export const ABOUT_US_PAGE_PATH = '/aboutus'
export const FEED_PAGE_PATH = '/feed'
export const PREDICTIONS_PAGE_PATH = '/predictions'
export const PROFILE_PAGE_PATH = '/profile'
